name: collaborative_todo
description: A collaborative TODO app with real-time task sharing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.0.5
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  
  # UI & Formatting
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  share_plus: ^7.1.0
  
  # Responsive design
  responsive_framework: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
