// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYiLw_rbGsl2Hdc9LbBvoTBJM4G7RMEPo',
    appId: '1:631482541003:web:22078533ca2d144616cc4e',
    messagingSenderId: '631482541003',
    projectId: 'collabrative-todo',
    authDomain: 'collabrative-todo.firebaseapp.com',
    storageBucket: 'collabrative-todo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7ZbD3Ac3bWNOFaYzHJSMkKFaNZC_UpM',
    appId: '1:631482541003:android:47ea21f6d998fbdf16cc4e',
    messagingSenderId: '631482541003',
    projectId: 'collabrative-todo',
    storageBucket: 'collabrative-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNYeU3s1YydEDPc07OMlWPPOq4c_Su1qY',
    appId: '1:631482541003:ios:e9ac77d4c02dc9de16cc4e',
    messagingSenderId: '631482541003',
    projectId: 'collabrative-todo',
    storageBucket: 'collabrative-todo.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNYeU3s1YydEDPc07OMlWPPOq4c_Su1qY',
    appId: '1:631482541003:ios:e9ac77d4c02dc9de16cc4e',
    messagingSenderId: '631482541003',
    projectId: 'collabrative-todo',
    storageBucket: 'collabrative-todo.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYiLw_rbGsl2Hdc9LbBvoTBJM4G7RMEPo',
    appId: '1:631482541003:web:b2a3acb48b4d758d16cc4e',
    messagingSenderId: '631482541003',
    projectId: 'collabrative-todo',
    authDomain: 'collabrative-todo.firebaseapp.com',
    storageBucket: 'collabrative-todo.firebasestorage.app',
  );
}
